### ISSUE TITLE
Modify `/metadata/validate` POST and all `/bulk` POST calls to support a job queue

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/ingest-api#305]
In the current implementation of the validate and bulk register endpoints we limit the number of rows in the provided TSV to 30 due to AWS timeout limitations. We should instead have these endpoints return a 202 status (processing) with a `run_id` and have these processes run for however long they need then update some sort of job queue when they have been finished. 

May have to investigate a thread-safe queue to run these processes or if that is even necessary. 

We could potentially utilize memcache to keep track of the queue where the key would be the concatenation of`run_id` and user email and  and the value be the JSON that those endpoints currently return.

**Comment by maxsibilla** [comment]
@tjmadonna has looked into this and Celery seems like a library that can help facilitate much of the job queue features. It works natively with Redis so instead of relying on memacached we can spin up 2 instances of Redis cache on AWS (for dev and prod). We can keep the existing memached infrastructure in place as these caches will serve two distinct roles on different microservices.

**Comment by tjmadonna** [comment]
#### Job/Task Queue
There are number of good message brokering and queuing libraries (RabbitMQ, ActiveMQ, Kafka etc...). Each of these would require us to create a separate subscriber in order to run our task. Our endpoint would create a task and the subscriber would pull that task from the queue to execute.

Celery is an all-in-one task queue that is written in Python. In order to run a task, a function can be decorated with the [`task` decorator](https://docs.celeryq.dev/en/stable/userguide/tasks.html#basics). The task function can then be ran. The task is queued using `Redis` (or other library) and eventually executed in a [worker server](https://docs.celeryq.dev/en/stable/getting-started/first-steps-with-celery.html#running-the-celery-worker-server). The results and status of the task can be store in `Redis` (or other library).

Celery seems to be the simplest way forward since our validation and registration function are already written in Python.

**Comment by tjmadonna** [comment]
- [ ] Delete job endpoint
- [ ] Job type in metadata
- [ ] Add user email in metadata for easier admin things
- [ ] Metadata register endpoint
- [ ] Single metadata validation/registration?
- [ ] Dockerize
